//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardver
    {
        public string SH { get; set; }
        public string CPU { get; set; }
        public Nullable<int> RAM { get; set; }
        public Nullable<int> HDD { get; set; }
    }
}
