//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekat
    {
        public string SP { get; set; }
        public System.DateTime DD { get; set; }
        public Nullable<System.DateTime> DP { get; set; }
        public Nullable<System.DateTime> RI { get; set; }
        public Nullable<int> KI { get; set; }
        public string SZ { get; set; }
    
        public virtual TimRadiNaProjektu TimRadiNaProjektus { get; set; }
    }
}
