//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectModelContainer : DbContext
    {
        public ProjectModelContainer()
            : base("name=ProjectModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Zaposleni> Zaposleni { get; set; }
        public virtual DbSet<PoslovniProstor> PoslovniProstori { get; set; }
        public virtual DbSet<Hardver> Hardveri { get; set; }
        public virtual DbSet<Tim> Timovi { get; set; }
        public virtual DbSet<Projekat> Projekati { get; set; }
        public virtual DbSet<TimRadiNaProjektu> TimRadiNaProjektu { get; set; }
    }
}
